project:
  type: website
  output-dir: _site

website:
  title: "Digital Sufism / التصوّف الرقميّ"
  site-url: https://digitalsufism.github.io
  repo-url: https://github.com/digitalsufism/digitalsufism.github.io
  favicon: img/sufi.png

  navbar:
    background: dark
    logo: img/sufi.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Bibliography"
        menu:
          - text: "Primary Sources"
            href: bibliography.qmd
          - text: "Secondary Scholarship"
            href: secondary.qmd
      - text: "About"
        href: about.qmd
    right:
      - text: "Contact"
        href: mailto:farrell.jedw@gmail.com
      - icon: github
        href: https://github.com/digitalsufism
        aria-label: GitHub

  page-footer:
    background: dark
    left: |
      © 2019–2025 Jeremy Farrell
    center: |
      [Attribution-NonCommercial – CC BY-NC](https://creativecommons.org/licenses/)
    right:
      - icon: envelope
        href: mailto:farrell.jedw@gmail.com
        aria-label: Email
      - icon: github
        href: https://github.com/digitalsufism
        aria-label: GitHub

  google-analytics: "UA-140121905-1"

  search:
    location: navbar
    type: textbox

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: false
    grid:
      body-width: 1000px
    lang: en
    link-external-newwindow: true
